### ISSUE TITLE
Find and Test APIs

### ISSUE THREAD

**Issue by ajrsabet** [ajrsabet/Screen_Time_Tracker#10]
Third Party API (1)
- [x] Moment.js
- [x] https://www.chartjs.org/
- [x] https://materializecss.com/

Server Side API (2)
- [x] Unsplash (search for images) https://unsplash.com/

- [x] youtube.com

**Comment by Crunchy126** [comment]
World Time API worldtimeapi.org
Unsplash (search for images) https://unsplash.com/
Animate.css
https://www.chartjs.org/

**Comment by ajrsabet** [comment]
ChartsJS.org
